version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '127.0.0.1:5432:5432'
  api:
    build:
      context: api
      dockerfile: ../api.Dockerfile
    depends_on:
      - db
    ports:
      - '127.0.0.1:8080:8080'
